export const personSeed = [
  {
    id: 1,
    name: 'Luke Skywalker',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 2,
    name: 'C-3PO',
    height: '167',
    mass: '75',
    hair_color: 'n\\/a',
    skin_color: 'gold',
    eye_color: 'yellow',
    birth_year: '112BBY',
    gender: 'n\\/a',
    created_on: null,
    updated_on: null,
  },
  {
    id: 3,
    name: 'R2-D2',
    height: '96',
    mass: '32',
    hair_color: 'n\\/a',
    skin_color: 'white, blue',
    eye_color: 'red',
    birth_year: '33BBY',
    gender: 'n\\/a',
    created_on: null,
    updated_on: null,
  },
  {
    id: 4,
    name: 'Darth Vader',
    height: '202',
    mass: '136',
    hair_color: 'none',
    skin_color: 'white',
    eye_color: 'yellow',
    birth_year: '41.9BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 5,
    name: 'Leia Organa',
    height: '150',
    mass: '49',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '19BBY',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 6,
    name: 'Owen Lars',
    height: '178',
    mass: '120',
    hair_color: 'brown, grey',
    skin_color: 'light',
    eye_color: 'blue',
    birth_year: '52BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 7,
    name: 'Beru Whitesun lars',
    height: '165',
    mass: '75',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'blue',
    birth_year: '47BBY',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 8,
    name: 'R5-D4',
    height: '97',
    mass: '32',
    hair_color: 'n\\/a',
    skin_color: 'white, red',
    eye_color: 'red',
    birth_year: 'unknown',
    gender: 'n\\/a',
    created_on: null,
    updated_on: null,
  },
  {
    id: 9,
    name: 'Biggs Darklighter',
    height: '183',
    mass: '84',
    hair_color: 'black',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '24BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 10,
    name: 'Obi-Wan Kenobi',
    height: '182',
    mass: '77',
    hair_color: 'auburn, white',
    skin_color: 'fair',
    eye_color: 'blue-gray',
    birth_year: '57BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 11,
    name: 'Anakin Skywalker',
    height: '188',
    mass: '84',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '41.9BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 12,
    name: 'Wilhuff Tarkin',
    height: '180',
    mass: 'unknown',
    hair_color: 'auburn, grey',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '64BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 13,
    name: 'Chewbacca',
    height: '228',
    mass: '112',
    hair_color: 'brown',
    skin_color: 'unknown',
    eye_color: 'blue',
    birth_year: '200BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 14,
    name: 'Han Solo',
    height: '180',
    mass: '80',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: '29BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 15,
    name: 'Greedo',
    height: '173',
    mass: '74',
    hair_color: 'n\\/a',
    skin_color: 'green',
    eye_color: 'black',
    birth_year: '44BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 16,
    name: 'Jabba Desilijic Tiure',
    height: '175',
    mass: '1,358',
    hair_color: 'n\\/a',
    skin_color: 'green-tan, brown',
    eye_color: 'orange',
    birth_year: '600BBY',
    gender: 'hermaphrodite',
    created_on: null,
    updated_on: null,
  },
  {
    id: 18,
    name: 'Wedge Antilles',
    height: '170',
    mass: '77',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'hazel',
    birth_year: '21BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 19,
    name: 'Jek Tono Porkins',
    height: '180',
    mass: '110',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 20,
    name: 'Yoda',
    height: '66',
    mass: '17',
    hair_color: 'white',
    skin_color: 'green',
    eye_color: 'brown',
    birth_year: '896BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 21,
    name: 'Palpatine',
    height: '170',
    mass: '75',
    hair_color: 'grey',
    skin_color: 'pale',
    eye_color: 'yellow',
    birth_year: '82BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 22,
    name: 'Boba Fett',
    height: '183',
    mass: '78.2',
    hair_color: 'black',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: '31.5BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 23,
    name: 'IG-88',
    height: '200',
    mass: '140',
    hair_color: 'none',
    skin_color: 'metal',
    eye_color: 'red',
    birth_year: '15BBY',
    gender: 'none',
    created_on: null,
    updated_on: null,
  },
  {
    id: 24,
    name: 'Bossk',
    height: '190',
    mass: '113',
    hair_color: 'none',
    skin_color: 'green',
    eye_color: 'red',
    birth_year: '53BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 25,
    name: 'Lando Calrissian',
    height: '177',
    mass: '79',
    hair_color: 'black',
    skin_color: 'dark',
    eye_color: 'brown',
    birth_year: '31BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 26,
    name: 'Lobot',
    height: '175',
    mass: '79',
    hair_color: 'none',
    skin_color: 'light',
    eye_color: 'blue',
    birth_year: '37BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 27,
    name: 'Ackbar',
    height: '180',
    mass: '83',
    hair_color: 'none',
    skin_color: 'brown mottle',
    eye_color: 'orange',
    birth_year: '41BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 28,
    name: 'Mon Mothma',
    height: '150',
    mass: 'unknown',
    hair_color: 'auburn',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '48BBY',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 29,
    name: 'Arvel Crynyd',
    height: 'unknown',
    mass: 'unknown',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 30,
    name: 'Wicket Systri Warrick',
    height: '88',
    mass: '20',
    hair_color: 'brown',
    skin_color: 'brown',
    eye_color: 'brown',
    birth_year: '8BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 31,
    name: 'Nien Nunb',
    height: '160',
    mass: '68',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 32,
    name: 'Qui-Gon Jinn',
    height: '193',
    mass: '89',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '92BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 33,
    name: 'Nute Gunray',
    height: '191',
    mass: '90',
    hair_color: 'none',
    skin_color: 'mottled green',
    eye_color: 'red',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 34,
    name: 'Finis Valorum',
    height: '170',
    mass: 'unknown',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '91BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 35,
    name: 'Padmé Amidala',
    height: '185',
    mass: '45',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '46BBY',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 36,
    name: 'Jar Jar Binks',
    height: '196',
    mass: '66',
    hair_color: 'none',
    skin_color: 'orange',
    eye_color: 'orange',
    birth_year: '52BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 37,
    name: 'Roos Tarpals',
    height: '224',
    mass: '82',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'orange',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 38,
    name: 'Rugor Nass',
    height: '206',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'green',
    eye_color: 'orange',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 39,
    name: 'Ric Olié',
    height: '183',
    mass: 'unknown',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 40,
    name: 'Watto',
    height: '137',
    mass: 'unknown',
    hair_color: 'black',
    skin_color: 'blue, grey',
    eye_color: 'yellow',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 41,
    name: 'Sebulba',
    height: '112',
    mass: '40',
    hair_color: 'none',
    skin_color: 'grey, red',
    eye_color: 'orange',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 42,
    name: 'Quarsh Panaka',
    height: '183',
    mass: 'unknown',
    hair_color: 'black',
    skin_color: 'dark',
    eye_color: 'brown',
    birth_year: '62BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 43,
    name: 'Shmi Skywalker',
    height: '163',
    mass: 'unknown',
    hair_color: 'black',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: '72BBY',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 44,
    name: 'Darth Maul',
    height: '175',
    mass: '80',
    hair_color: 'none',
    skin_color: 'red',
    eye_color: 'yellow',
    birth_year: '54BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 45,
    name: 'Bib Fortuna',
    height: '180',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'pale',
    eye_color: 'pink',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 46,
    name: 'Ayla Secura',
    height: '178',
    mass: '55',
    hair_color: 'none',
    skin_color: 'blue',
    eye_color: 'hazel',
    birth_year: '48BBY',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 47,
    name: 'Ratts Tyerel',
    height: '79',
    mass: '15',
    hair_color: 'none',
    skin_color: 'grey, blue',
    eye_color: 'unknown',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 48,
    name: 'Dud Bolt',
    height: '94',
    mass: '45',
    hair_color: 'none',
    skin_color: 'blue, grey',
    eye_color: 'yellow',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 49,
    name: 'Gasgano',
    height: '122',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'white, blue',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 50,
    name: 'Ben Quadinaros',
    height: '163',
    mass: '65',
    hair_color: 'none',
    skin_color: 'grey, green, yellow',
    eye_color: 'orange',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 51,
    name: 'Mace Windu',
    height: '188',
    mass: '84',
    hair_color: 'none',
    skin_color: 'dark',
    eye_color: 'brown',
    birth_year: '72BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 52,
    name: 'Ki-Adi-Mundi',
    height: '198',
    mass: '82',
    hair_color: 'white',
    skin_color: 'pale',
    eye_color: 'yellow',
    birth_year: '92BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 53,
    name: 'Kit Fisto',
    height: '196',
    mass: '87',
    hair_color: 'none',
    skin_color: 'green',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 54,
    name: 'Eeth Koth',
    height: '171',
    mass: 'unknown',
    hair_color: 'black',
    skin_color: 'brown',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 55,
    name: 'Adi Gallia',
    height: '184',
    mass: '50',
    hair_color: 'none',
    skin_color: 'dark',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 56,
    name: 'Saesee Tiin',
    height: '188',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'pale',
    eye_color: 'orange',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 57,
    name: 'Yarael Poof',
    height: '264',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'white',
    eye_color: 'yellow',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 58,
    name: 'Plo Koon',
    height: '188',
    mass: '80',
    hair_color: 'none',
    skin_color: 'orange',
    eye_color: 'black',
    birth_year: '22BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 59,
    name: 'Mas Amedda',
    height: '196',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'blue',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 60,
    name: 'Gregar Typho',
    height: '185',
    mass: '85',
    hair_color: 'black',
    skin_color: 'dark',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 61,
    name: 'Cordé',
    height: '157',
    mass: 'unknown',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 62,
    name: 'Cliegg Lars',
    height: '183',
    mass: 'unknown',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '82BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 63,
    name: 'Poggle the Lesser',
    height: '183',
    mass: '80',
    hair_color: 'none',
    skin_color: 'green',
    eye_color: 'yellow',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 64,
    name: 'Luminara Unduli',
    height: '170',
    mass: '56.2',
    hair_color: 'black',
    skin_color: 'yellow',
    eye_color: 'blue',
    birth_year: '58BBY',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 65,
    name: 'Barriss Offee',
    height: '166',
    mass: '50',
    hair_color: 'black',
    skin_color: 'yellow',
    eye_color: 'blue',
    birth_year: '40BBY',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 66,
    name: 'Dormé',
    height: '165',
    mass: 'unknown',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 67,
    name: 'Dooku',
    height: '193',
    mass: '80',
    hair_color: 'white',
    skin_color: 'fair',
    eye_color: 'brown',
    birth_year: '102BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 68,
    name: 'Bail Prestor Organa',
    height: '191',
    mass: 'unknown',
    hair_color: 'black',
    skin_color: 'tan',
    eye_color: 'brown',
    birth_year: '67BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 69,
    name: 'Jango Fett',
    height: '183',
    mass: '79',
    hair_color: 'black',
    skin_color: 'tan',
    eye_color: 'brown',
    birth_year: '66BBY',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 70,
    name: 'Zam Wesell',
    height: '168',
    mass: '55',
    hair_color: 'blonde',
    skin_color: 'fair, green, yellow',
    eye_color: 'yellow',
    birth_year: 'unknown',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 71,
    name: 'Dexter Jettster',
    height: '198',
    mass: '102',
    hair_color: 'none',
    skin_color: 'brown',
    eye_color: 'yellow',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 72,
    name: 'Lama Su',
    height: '229',
    mass: '88',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 73,
    name: 'Taun We',
    height: '213',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 74,
    name: 'Jocasta Nu',
    height: '167',
    mass: 'unknown',
    hair_color: 'white',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 75,
    name: 'R4-P17',
    height: '96',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'silver, red',
    eye_color: 'red, blue',
    birth_year: 'unknown',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 76,
    name: 'Wat Tambor',
    height: '193',
    mass: '48',
    hair_color: 'none',
    skin_color: 'green, grey',
    eye_color: 'unknown',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 77,
    name: 'San Hill',
    height: '191',
    mass: 'unknown',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'gold',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 78,
    name: 'Shaak Ti',
    height: '178',
    mass: '57',
    hair_color: 'none',
    skin_color: 'red, blue, white',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 79,
    name: 'Grievous',
    height: '216',
    mass: '159',
    hair_color: 'none',
    skin_color: 'brown, white',
    eye_color: 'green, yellow',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 80,
    name: 'Tarfful',
    height: '234',
    mass: '136',
    hair_color: 'brown',
    skin_color: 'brown',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 81,
    name: 'Raymus Antilles',
    height: '188',
    mass: '79',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
  {
    id: 82,
    name: 'Sly Moore',
    height: '178',
    mass: '48',
    hair_color: 'none',
    skin_color: 'pale',
    eye_color: 'white',
    birth_year: 'unknown',
    gender: 'female',
    created_on: null,
    updated_on: null,
  },
  {
    id: 83,
    name: 'Tion Medon',
    height: '206',
    mass: '80',
    hair_color: 'none',
    skin_color: 'grey',
    eye_color: 'black',
    birth_year: 'unknown',
    gender: 'male',
    created_on: null,
    updated_on: null,
  },
];

export const filmSeed = [
  {
    id: 3,
    name: 'Revenge of the Sith',
    director: 'George Lucas',
    producer: 'Rick McCallum',
    release_date: '2005-05-19',
    created_on: '2014-12-20T20:49:38.403Z',
    updated_on: '2014-12-20T22:47:52.073Z',
    description:
      'War! The Republic is crumbling\\r\\nunder attacks by the ruthless\\r\\nSith Lord, Count Dooku.\\r\\nThere are heroes on both sides.\\r\\nEvil is everywhere.\\r\\n\\r\\nIn a stunning move, the\\r\\nfiendish droid leader, General\\r\\nGrievous, has swept into the\\r\\nRepublic capital and kidnapped\\r\\nChancellor Palpatine, leader of\\r\\nthe Galactic Senate.\\r\\n\\r\\nAs the Separatist Droid Army\\r\\nattempts to flee the besieged\\r\\ncapital with their valuable\\r\\nhostage, two Jedi Knights lead a\\r\\ndesperate mission to rescue the\\r\\ncaptive Chancellor....',
  },
  {
    id: 2,
    name: 'Attack of the Clones',
    director: 'George Lucas',
    producer: 'Rick McCallum',
    release_date: '2002-05-16',
    created_on: '2025-04-22T21:40:52.770Z',
    updated_on: '2025-04-22T21:40:52.770Z',
    description:
      'There is unrest in the Galactic\\r\\nSenate. Several thousand solar\\r\\nsystems have declared their\\r\\nintentions to leave the Republic.\\r\\n\\r\\nThis separatist movement,\\r\\nunder the leadership of the\\r\\nmysterious Count Dooku, has\\r\\nmade it difficult for the limited\\r\\nnumber of Jedi Knights to maintain \\r\\npeace and order in the galaxy.\\r\\n\\r\\nSenator Amidala, the former\\r\\nQueen of Naboo, is returning\\r\\nto the Galactic Senate to vote\\r\\non the critical issue of creating\\r\\nan ARMY OF THE REPUBLIC\\r\\nto assist the overwhelmed\\r\\nJedi...',
  },
  {
    id: 1,
    name: 'The Phantom Menace',
    director: 'George Lucas',
    producer: 'Rick McCallum',
    release_date: '1999-05-19',
    created_on: '2025-04-22T21:40:55.030Z',
    updated_on: '2025-04-22T21:40:55.030Z',
    description:
      'Turmoil has engulfed the\\r\\nGalactic Republic. The taxation\\r\\nof trade routes to outlying star\\r\\nsystems is in dispute.\\r\\n\\r\\nHoping to resolve the matter\\r\\nwith a blockade of deadly\\r\\nbattleships, the greedy Trade\\r\\nFederation has stopped all\\r\\nshipping to the small planet\\r\\nof Naboo.\\r\\n\\r\\nWhile the Congress of the\\r\\nRepublic endlessly debates\\r\\nthis alarming chain of events,\\r\\nthe Supreme Chancellor has\\r\\nsecretly dispatched two Jedi\\r\\nKnights, the guardians of\\r\\npeace and justice in the\\r\\ngalaxy, to settle the conflict...',
  },
  {
    id: 6,
    name: 'Return of the Jedi',
    director: 'Richard Marquand',
    producer: 'Howard G. Kazanjian, George Lucas, Rick McCallum',
    release_date: '1983-05-25',
    created_on: '2025-04-22T21:40:57.199Z',
    updated_on: '2025-04-22T21:40:57.199Z',
    description:
      'Luke Skywalker has returned to\\r\\nhis home planet of Tatooine in\\r\\nan attempt to rescue his\\r\\nfriend Han Solo from the\\r\\nclutches of the vile gangster\\r\\nJabba the Hutt.\\r\\n\\r\\nLittle does Luke know that the\\r\\nGALACTIC EMPIRE has secretly\\r\\nbegun construction on a new\\r\\narmored space station even\\r\\nmore powerful than the first\\r\\ndreaded Death Star.\\r\\n\\r\\nWhen completed, this ultimate\\r\\nweapon will spell certain doom\\r\\nfor the small band of rebels\\r\\nstruggling to restore freedom\\r\\nto the galaxy...',
  },
  {
    id: 5,
    name: 'The Empire Strikes Back',
    director: 'Irvin Kershner',
    producer: 'Gary Kurtz, Rick McCallum',
    release_date: '1980-05-17',
    created_on: '2025-04-22T21:40:59.979Z',
    updated_on: '2025-04-22T21:40:59.979Z',
    description:
      'It is a dark time for the\\r\\nRebellion. Although the Death\\r\\nStar has been destroyed,\\r\\nImperial troops have driven the\\r\\nRebel forces from their hidden\\r\\nbase and pursued them across\\r\\nthe galaxy.\\r\\n\\r\\nEvading the dreaded Imperial\\r\\nStarfleet, a group of freedom\\r\\nfighters led by Luke Skywalker\\r\\nhas established a new secret\\r\\nbase on the remote ice world\\r\\nof Hoth.\\r\\n\\r\\nThe evil lord Darth Vader,\\r\\nobsessed with finding young\\r\\nSkywalker, has dispatched\\r\\nthousands of remote probes into\\r\\nthe far reaches of space...',
  },
  {
    id: 4,
    name: 'A New Hope',
    director: 'George Lucas',
    producer: 'Gary Kurtz, Rick McCallum',
    release_date: '1977-05-25',
    created_on: '2025-04-22T21:42:03.127Z',
    updated_on: '2025-04-22T21:42:03.127Z',
    description:
      "It is a period of civil war.\\r\\nRebel spaceships, striking\\r\\nfrom a hidden base, have won\\r\\ntheir first victory against\\r\\nthe evil Galactic Empire.\\r\\n\\r\\nDuring the battle, Rebel\\r\\nspies managed to steal secret\\r\\nplans to the Empire's\\r\\nultimate weapon, the DEATH\\r\\nSTAR, an armored space\\r\\nstation with enough power\\r\\nto destroy an entire planet.\\r\\n\\r\\nPursued by the Empire's\\r\\nsinister agents, Princess\\r\\nLeia races home aboard her\\r\\nstarship, custodian of the\\r\\nstolen plans that can save her\\r\\npeople and restore\\r\\nfreedom to the galaxy...",
  },
];

export const filmPersonSeed = [
  {
    film_id: 4,
    person_id: 1,
  },
  {
    film_id: 4,
    person_id: 2,
  },
  {
    film_id: 4,
    person_id: 3,
  },
  {
    film_id: 4,
    person_id: 4,
  },
  {
    film_id: 4,
    person_id: 5,
  },
  {
    film_id: 4,
    person_id: 6,
  },
  {
    film_id: 4,
    person_id: 7,
  },
  {
    film_id: 4,
    person_id: 8,
  },
  {
    film_id: 4,
    person_id: 9,
  },
  {
    film_id: 4,
    person_id: 10,
  },
  {
    film_id: 4,
    person_id: 12,
  },
  {
    film_id: 4,
    person_id: 13,
  },
  {
    film_id: 4,
    person_id: 14,
  },
  {
    film_id: 4,
    person_id: 15,
  },
  {
    film_id: 4,
    person_id: 16,
  },
  {
    film_id: 4,
    person_id: 18,
  },
  {
    film_id: 4,
    person_id: 19,
  },
  {
    film_id: 4,
    person_id: 81,
  },
  {
    film_id: 5,
    person_id: 1,
  },
  {
    film_id: 5,
    person_id: 2,
  },
  {
    film_id: 5,
    person_id: 3,
  },
  {
    film_id: 5,
    person_id: 4,
  },
  {
    film_id: 5,
    person_id: 5,
  },
  {
    film_id: 5,
    person_id: 10,
  },
  {
    film_id: 5,
    person_id: 13,
  },
  {
    film_id: 5,
    person_id: 14,
  },
  {
    film_id: 5,
    person_id: 18,
  },
  {
    film_id: 5,
    person_id: 20,
  },
  {
    film_id: 5,
    person_id: 21,
  },
  {
    film_id: 5,
    person_id: 22,
  },
  {
    film_id: 5,
    person_id: 23,
  },
  {
    film_id: 5,
    person_id: 24,
  },
  {
    film_id: 5,
    person_id: 25,
  },
  {
    film_id: 5,
    person_id: 26,
  },
  {
    film_id: 6,
    person_id: 1,
  },
  {
    film_id: 6,
    person_id: 2,
  },
  {
    film_id: 6,
    person_id: 3,
  },
  {
    film_id: 6,
    person_id: 4,
  },
  {
    film_id: 6,
    person_id: 5,
  },
  {
    film_id: 6,
    person_id: 10,
  },
  {
    film_id: 6,
    person_id: 13,
  },
  {
    film_id: 6,
    person_id: 14,
  },
  {
    film_id: 6,
    person_id: 16,
  },
  {
    film_id: 6,
    person_id: 18,
  },
  {
    film_id: 6,
    person_id: 20,
  },
  {
    film_id: 6,
    person_id: 21,
  },
  {
    film_id: 6,
    person_id: 22,
  },
  {
    film_id: 6,
    person_id: 25,
  },
  {
    film_id: 6,
    person_id: 27,
  },
  {
    film_id: 6,
    person_id: 28,
  },
  {
    film_id: 6,
    person_id: 29,
  },
  {
    film_id: 6,
    person_id: 30,
  },
  {
    film_id: 6,
    person_id: 31,
  },
  {
    film_id: 6,
    person_id: 45,
  },
  {
    film_id: 1,
    person_id: 2,
  },
  {
    film_id: 1,
    person_id: 3,
  },
  {
    film_id: 1,
    person_id: 10,
  },
  {
    film_id: 1,
    person_id: 11,
  },
  {
    film_id: 1,
    person_id: 16,
  },
  {
    film_id: 1,
    person_id: 20,
  },
  {
    film_id: 1,
    person_id: 21,
  },
  {
    film_id: 1,
    person_id: 32,
  },
  {
    film_id: 1,
    person_id: 33,
  },
  {
    film_id: 1,
    person_id: 34,
  },
  {
    film_id: 1,
    person_id: 35,
  },
  {
    film_id: 1,
    person_id: 36,
  },
  {
    film_id: 1,
    person_id: 37,
  },
  {
    film_id: 1,
    person_id: 38,
  },
  {
    film_id: 1,
    person_id: 39,
  },
  {
    film_id: 1,
    person_id: 40,
  },
  {
    film_id: 1,
    person_id: 41,
  },
  {
    film_id: 1,
    person_id: 42,
  },
  {
    film_id: 1,
    person_id: 43,
  },
  {
    film_id: 1,
    person_id: 44,
  },
  {
    film_id: 1,
    person_id: 46,
  },
  {
    film_id: 1,
    person_id: 47,
  },
  {
    film_id: 1,
    person_id: 48,
  },
  {
    film_id: 1,
    person_id: 49,
  },
  {
    film_id: 1,
    person_id: 50,
  },
  {
    film_id: 1,
    person_id: 51,
  },
  {
    film_id: 1,
    person_id: 52,
  },
  {
    film_id: 1,
    person_id: 53,
  },
  {
    film_id: 1,
    person_id: 54,
  },
  {
    film_id: 1,
    person_id: 55,
  },
  {
    film_id: 1,
    person_id: 56,
  },
  {
    film_id: 1,
    person_id: 57,
  },
  {
    film_id: 1,
    person_id: 58,
  },
  {
    film_id: 1,
    person_id: 59,
  },
  {
    film_id: 2,
    person_id: 2,
  },
  {
    film_id: 2,
    person_id: 3,
  },
  {
    film_id: 2,
    person_id: 6,
  },
  {
    film_id: 2,
    person_id: 7,
  },
  {
    film_id: 2,
    person_id: 10,
  },
  {
    film_id: 2,
    person_id: 11,
  },
  {
    film_id: 2,
    person_id: 20,
  },
  {
    film_id: 2,
    person_id: 21,
  },
  {
    film_id: 2,
    person_id: 22,
  },
  {
    film_id: 2,
    person_id: 33,
  },
  {
    film_id: 2,
    person_id: 35,
  },
  {
    film_id: 2,
    person_id: 36,
  },
  {
    film_id: 2,
    person_id: 40,
  },
  {
    film_id: 2,
    person_id: 43,
  },
  {
    film_id: 2,
    person_id: 46,
  },
  {
    film_id: 2,
    person_id: 51,
  },
  {
    film_id: 2,
    person_id: 52,
  },
  {
    film_id: 2,
    person_id: 53,
  },
  {
    film_id: 2,
    person_id: 58,
  },
  {
    film_id: 2,
    person_id: 59,
  },
  {
    film_id: 2,
    person_id: 60,
  },
  {
    film_id: 2,
    person_id: 61,
  },
  {
    film_id: 2,
    person_id: 62,
  },
  {
    film_id: 2,
    person_id: 63,
  },
  {
    film_id: 2,
    person_id: 64,
  },
  {
    film_id: 2,
    person_id: 65,
  },
  {
    film_id: 2,
    person_id: 66,
  },
  {
    film_id: 2,
    person_id: 67,
  },
  {
    film_id: 2,
    person_id: 68,
  },
  {
    film_id: 2,
    person_id: 69,
  },
  {
    film_id: 2,
    person_id: 70,
  },
  {
    film_id: 2,
    person_id: 71,
  },
  {
    film_id: 2,
    person_id: 72,
  },
  {
    film_id: 2,
    person_id: 73,
  },
  {
    film_id: 2,
    person_id: 74,
  },
  {
    film_id: 2,
    person_id: 75,
  },
  {
    film_id: 2,
    person_id: 76,
  },
  {
    film_id: 2,
    person_id: 77,
  },
  {
    film_id: 2,
    person_id: 78,
  },
  {
    film_id: 2,
    person_id: 82,
  },
  {
    film_id: 3,
    person_id: 1,
  },
  {
    film_id: 3,
    person_id: 2,
  },
  {
    film_id: 3,
    person_id: 3,
  },
  {
    film_id: 3,
    person_id: 4,
  },
  {
    film_id: 3,
    person_id: 5,
  },
  {
    film_id: 3,
    person_id: 6,
  },
  {
    film_id: 3,
    person_id: 7,
  },
  {
    film_id: 3,
    person_id: 10,
  },
  {
    film_id: 3,
    person_id: 11,
  },
  {
    film_id: 3,
    person_id: 12,
  },
  {
    film_id: 3,
    person_id: 13,
  },
  {
    film_id: 3,
    person_id: 20,
  },
  {
    film_id: 3,
    person_id: 21,
  },
  {
    film_id: 3,
    person_id: 33,
  },
  {
    film_id: 3,
    person_id: 35,
  },
  {
    film_id: 3,
    person_id: 46,
  },
  {
    film_id: 3,
    person_id: 51,
  },
  {
    film_id: 3,
    person_id: 52,
  },
  {
    film_id: 3,
    person_id: 53,
  },
  {
    film_id: 3,
    person_id: 54,
  },
  {
    film_id: 3,
    person_id: 55,
  },
  {
    film_id: 3,
    person_id: 56,
  },
  {
    film_id: 3,
    person_id: 58,
  },
  {
    film_id: 3,
    person_id: 63,
  },
  {
    film_id: 3,
    person_id: 64,
  },
  {
    film_id: 3,
    person_id: 67,
  },
  {
    film_id: 3,
    person_id: 68,
  },
  {
    film_id: 3,
    person_id: 75,
  },
  {
    film_id: 3,
    person_id: 78,
  },
  {
    film_id: 3,
    person_id: 79,
  },
  {
    film_id: 3,
    person_id: 80,
  },
  {
    film_id: 3,
    person_id: 81,
  },
  {
    film_id: 3,
    person_id: 82,
  },
  {
    film_id: 3,
    person_id: 83,
  },
];
